### ISSUE TITLE
Media Attachments for Remote Accounts "Not Available"

### ISSUE THREAD

**Issue by a-dows** [tootsuite/mastodon#13739]
A seemingly random assortment of image previews from followed remote accounts are failing to generate previews. The issue persists in all browsers and apps. 

No errors appear in the console when viewed in a desktop browser; the images are available on clickthrough. Opening the status in its own local url renders all previews normally.

Loading the same remote status in two different instances produces different missing image previews, though at least one preview remains missing (see second photo).

Problem observed in Mastodon 3.1.2 as well as 3.1.3. Users first reported this issue to me as an admin about two weeks ago.

Reported remote instances displaying the issue include mastodon.social, skull.website, and godforsaken.website.

![dd2f84d8581cf3b4](https://user-images.githubusercontent.com/42701400/81561030-870ad900-9360-11ea-98e5-d91359083ecb.jpeg)
![a5efc5d843dd8100](https://user-images.githubusercontent.com/42701400/81561267-ee288d80-9360-11ea-9c47-4725495cd803.png)

**Comment by Moth-Tolias** [comment]
i've run into this several times on my instance, chitter.xyz.

**Comment by fcashman** [comment]
Yep, reported this to my admin last week on cooler.mom. And the occurrence is inconsistent. The picture will be unavailable in a post and then later from the same account a new post's picture is unaffected. The picture must be clicked on and opened in separate tab to be viewed. I use Mastodon through the browser on both my desktop (MacOS Mojave and on my iPhone (pinned to my homescreen). I have not seen this issue in Amaroq, which is on my phone (but I hardly use it except now to see if pictures are loading). I need to keep checking Amaroq to see if this claim is 100% true. Also Amaroq hasn't been updated in 11 months, so maybe that is the reason.

**Comment by lawremipsum** [comment]
I've seen this, and have not noticed any pattern to its occurence.

**Comment by davidwolfpaw** [comment]
This happens to me regularly on tech.lgbt, and is not a new occurrence

**Comment by snoozysoft** [comment]
Can confirm it's occurring on cybre.space also.

**Comment by bclindner** [comment]
mastodon.technology also has this issue - glad to hear it isn't just us.

**Comment by ThibG** [comment]
This happens when the remote media couldn't be fetched/saved by Mastodon. It may either be an issue in the underlying media handling code, or more probably, just the originating instance being overwhelmed by follower instances trying to fetch the media at the same time.

Normally, Mastodon should retry a few times for each failed fetch, meaning the media can “unbreak” later.

**Comment by a-dows** [comment]
@ThibG It's been increasing in frequency lately, per user reports, and it doesn't appear possible to force a retry. The documentation for preview cards in the CLI specifically advises against doing anything with card data less than 7 days old.

**Comment by ThibG** [comment]
Note that those aren't preview cards, but media attachments. Preview cards are the thing where Mastodon crawls a link present in the toot text to display a preview of such link.

**Comment by a-dows** [comment]
@ThibG Thanks—fixed the title.

**Comment by ThibG** [comment]
Also it should be possible to re-fetch the media attached to a specific status by running `tootctl media refresh --status=id` (where `id` is the numeric identifier of the status on the *receiving* instance, such as you can see in the URL when viewing the status in the WebUI).
Of course this isn't a viable solution to fetch missing media on an everyday basis, but it should at least help figuring out whether the issue is transient (e.g., originating instance too slow to serve the media) or a reproducible issue with the media handling itself.

**Comment by a-dows** [comment]
@ThibG So I ran media refresh ID on an affected post. It did nothing. 

Local url:
https://dads.cool/web/statuses/104150363538006622
Remote url:
https://skull.website/@Pixley/104150362454628540

```
mastodon@localhost:~/live$ RAILS_ENV=production bin/tootctl media refresh --status=104150363538006622 --verbose
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Processing 181872                                
Processing 181873                |  ETA: ??:??:??
2/2 |============================| Time: 00:00:00
Downloaded 2 media attachments (approx. 0 Bytes)
```

Then I ran it with the --force tag, just in case:

```
mastodon@localhost:~/live$ RAILS_ENV=production bin/tootctl media refresh --status=104150363538006622 --verbose --force
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Processing 181872                                                                                       
Processing 181873                                                                                       
2/2 |===================================================================================| Time: 00:00:00
Downloaded 2 media attachments (approx. 213 KB)
```
This, too, did nothing.

I reloaded the status in multiple browsers, including private windows without cache.

**Comment by ThibG** [comment]
The fact that it doesn't help is interesting. I cannot reproduce it, though :/

If you run `bundle exec rails c RAILS_ENV=production` and, within it, the following commands: `MediaAttachment.find(181872).pluck(:remote_url, :file_file_name, :type, :processing, :file_meta)`, what does it return?

**Comment by a-dows** [comment]
```
mastodon@localhost:~/live$ RAILS_ENV=production bundle exec rails console
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Chewy console strategy is `urgent`
Loading production environment (Rails 5.2.4.1)
irb(main):001:0> MediaAttachment.find(181872).pluck(:remote_url, :file_file_name, :type, :processing, :file_meta)
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `pluck' for #<MediaAttachment:0x000056155a25e318>)
irb(main):002:0> 
```

**Comment by ThibG** [comment]
Ah sorry, I meant
`MediaAttachment.where(id: [181872, 181873]).pluck(:remote_url, :file_file_name, :type, :processing, :file_meta])`

**Comment by a-dows** [comment]
```
irb(main):009:0> MediaAttachment.where(id: [181872, 181873]).pluck(:remote_url, :file_file_name, :type, :processing, :file_meta)
Traceback (most recent call last):
        2: from (irb):9
        1: from (irb):9:in `rescue in irb_binding'
ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "processing" does not exist)
LINE 1: ...ts"."file_file_name", "media_attachments"."type", "processin...
                                                             ^
: SELECT "media_attachments"."remote_url", "media_attachments"."file_file_name", "media_attachments"."type", "processing", "media_attachments"."file_meta" FROM "media_attachments" WHERE "media_attachments"."id" IN ($1, $2) ORDER BY "media_attachments"."id" ASC
irb(main):010:0> 
```

**Comment by ThibG** [comment]
Ah, you're still on v3.1.2… try the same thing without `:processing` then

**Comment by a-dows** [comment]
```
irb(main):001:0> MediaAttachment.where(id: [181872, 181873]).pluck(:remote_url, :file_file_name, :type, :file_meta)
=> [["https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/skullwebsite/media_attachments/files/000/173/356/original/6286945ae4532280.jpg", "35d84615834cde6f.jpeg", "image", {"original"=>{"width"=>1129, "height"=>1451, "size"=>"1129x1451", "aspect"=>0.7780840799448656}, "small"=>{"width"=>352, "height"=>453, "size"=>"352x453", "aspect"=>0.7770419426048565}}], ["https://cf.mastohost.com/v1/AUTH_91eb37814936490c95da7b85993cc2ff/skullwebsite/media_attachments/files/000/173/357/original/541e181a043c2f98.jpg", nil, "unknown", nil]]
irb(main):002:0> 
```

**Comment by ThibG** [comment]
what does the following do?
```ruby
attachment = MediaAttachment.find(181873)
attachment.reset_file!
attachment.save!
```

**Comment by Restioson** [comment]
Opening it as a link works usually.

**Comment by a-dows** [comment]
```
irb(main):002:0> attachment = MediaAttachment.find(181873)
=> #<MediaAttachment id: 181873, status_id: 104150363538006622, file_file_name: nil, file_content_type: nil, file_file_size: nil, file_updated_at: nil, remote_url: "https://cf.mastohost.com/v1/AUTH_91eb37814936490c9...", created_at: "2020-05-11 14:46:57", updated_at: "2020-05-11 14:47:08", shortcode: nil, type: "unknown", file_meta: nil, account_id: 19719, description: "The black and orange bird is leaning down to nibbl...", scheduled_status_id: nil, blurhash: "UANKFv~p4o-;00fSRkbI00xuD%V?NGR*WAad">
irb(main):003:0> attachment.reset_file!
=> nil
irb(main):004:0> attachment.save!
=> true
irb(main):005:0> 
```

**Comment by ThibG** [comment]
Hmm… did that download the file?

**Comment by a-dows** [comment]
No, it did not.

**Comment by ThibG** [comment]
Ok. Can you retry the `reset_file!` within `RAILS_ENV=production RAILS_LOG_LEVEL=debug bundle exec c`? Hopefully, if something fails in the download, we'll get more info.

**Comment by BalooUriza** [comment]
This is also occurring on social.tulsa.ok.us

**Comment by a-dows** [comment]
```
mastodon@localhost:~/live$ RAILS_ENV=production RAILS_LOG_LEVEL=debug bundle exec rails console
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
/home/mastodon/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/bundler-1.17.2/lib/bundler/rubygems_integration.rb:200: warning: constant Gem::ConfigMap is deprecated
Chewy console strategy is `urgent`
Loading production environment (Rails 5.2.4.1)
irb(main):001:0> attachment = MediaAttachment.find(181873)
  MediaAttachment Load (1.6ms)  SELECT  "media_attachments".* FROM "media_attachments" WHERE "media_attachments"."id" = $1 ORDER BY "media_attachments"."id" ASC LIMIT $2  [["id", 181873], ["LIMIT", 1]]
=> #<MediaAttachment id: 181873, status_id: 104150363538006622, file_file_name: nil, file_content_type: nil, file_file_size: nil, file_updated_at: nil, remote_url: "https://cf.mastohost.com/v1/AUTH_91eb37814936490c9...", created_at: "2020-05-11 14:46:57", updated_at: "2020-05-11 14:47:08", shortcode: nil, type: "unknown", file_meta: nil, account_id: 19719, description: "The black and orange bird is leaning down to nibbl...", scheduled_status_id: nil, blurhash: "UANKFv~p4o-;00fSRkbI00xuD%V?NGR*WAad">
irb(main):002:0> attachment.reset_file!
=> nil
irb(main):003:0> attachment.save!
   (0.5ms)  BEGIN
  Account Load (1.9ms)  SELECT  "accounts".* FROM "accounts" WHERE "accounts"."id" = $1 LIMIT $2  [["id", 19719], ["LIMIT", 1]]
   (0.8ms)  COMMIT
=> true
irb(main):004:0> 
```

**Comment by ThibG** [comment]
Thank you! I believe @noellabo has found the issue and it will soon be fixed (see #13741).

Basically, what is happening is that the re-download function is broken for media attachments, so temporary failures are *not* properly corrected.

**Comment by ThibG** [comment]
Fixed by #13741

**Comment by phocks** [comment]
Can confirm still happening even after "fix #13741" merge. I thought it was due to image size, but nope it seems to happen at random, no matter the image size.

**Comment by smiba** [comment]
Just observed this over at my instance as well, a single image from an account that works fine otherwise. Other instances seems to have obtained it just fine, it happens seemingly at random

**Comment by danorton** [comment]
This is still happening on v4.0.2

**Comment by Visne** [comment]
Still seems to be happening for me a lot on v4.2.1.

**Comment by awg13** [comment]
Still happening it on v4.2.3. Wish there's a fix for this. 
Not sure if this has to do something with the distance between the s3 bucket location (US) and the server location (Asia).

**Comment by Visne** [comment]
@ClearlyClaire Could this issue be re-opened?

**Comment by hl0dwig** [comment]
using "bin/tootctl media refresh --status=ID" where ID is the one of the problematic post is resolving the problem... but still we shouldn't have to do it manually

**Comment by smiba** [comment]
We're still running tootctl media refresh --days 0.2 every hour or so in a crontab fwiw, makes it less obvious there are  broken images unless you're actively watching your timeline before it runs.

`RAILS_ENV=production /home/mastodon/live/bin/tootctl media refresh --days 0.2`

(or how we run it: `RAILS_ENV=production nice -n 10 flock -x /home/mastodon/.tootctl.lock -c '/home/mastodon/live/bin/tootctl media refresh --days 0.2'`)

**Comment by ClearlyClaire** [comment]
> In general retrying the dead jobs in sidekiq with "Seahorse::Client::NetworkingError" fixes these images, but I'm not sure why they weren't retried in the first place.

Pushed #28714 to address this (media download failing because of a transient S3 error).

**Comment by smiba** [comment]
Unfortunately still seeing some broken images even with #28714, wonder what's going on. Seems random, getting the image through media_proxy (or running tootctl media refresh) fixes them

**Comment by Harvey-Ai** [comment]
hello there, i have encountered the same problem, i created a instance, and it can't show any image or media_attachement from other server. 
i manually do the refreshe, but nothing downloaded.

RAILS_ENV=production  bin/tootctl media refresh --days 0.2
26/26 |=============================================================| Time: 00:00:00
Downloaded 26 media attachments (approx. 0 Bytes)

i don't what cuase this?

**Comment by smiba** [comment]
If all external images fail you're probably looking into some other issue, the approx. 0 Bytes suggest to me that Mastodon considers all 26 attachments to be up to date and have not been redownloaded. 

Are you confident the issue is with the backend? You can try running it with `--force` but I think it's unlikely this would make a difference.

**Comment by Harvey-Ai** [comment]
i manully rerun it with --force, it downloaded downloaded some images(not all that in blur), so the problem is bandwidth intensive? 
thx for reply.

RAILS_ENV=production bin/tootctl media refresh --days 0.2 --force
13/13 |=================================================================================| Time: 00:00:27
Downloaded 13 media attachments (approx. 6.16 MB)

**Comment by smiba** [comment]
Did this actually fix your issue? Keep in mind that `--force` will **always** result in tootctl (re-)downloading said images, the fact it downloaded 6.16MB this run doesn't mean it has resolved any actual issues. 

>so the problem is bandwidth intensive?

Constantly running this command with `--force` is not an acceptable solution, if this actually resolved any issues there is a deeper problem that should be looked into. I've never seen mastodon mark external content as successfully processed (where it doesn't consider any of the files in need to be redownloaded) through tootctl while this is not actually the case.

If you click on any of the images that are "blurry", does Mastodon redirect you to the image hosted on the source instance, or does it give you a 404 (originating from your host). Just want to rule out media cache issues on your webserver's side

**Comment by Harvey-Ai** [comment]
> Did this actually fix your issue? Keep in mind that `--force` will **always** result in tootctl (re-)downloading said images, the fact it downloaded 6.16MB this run doesn't mean it has resolved any actual issues.
> 
> > so the problem is bandwidth intensive?
> 
> Constantly running this command with `--force` is not an acceptable solution, if this actually resolved any issues there is a deeper problem that should be looked into. I've never seen mastodon mark external content as successfully processed (where it doesn't consider any of the files in need to be redownloaded) through tootctl while this is not actually the case.
> 
> If you click on any of the images that are "blurry", does Mastodon redirect you to the image hosted on the source instance, or does it give you a 404 (originating from your host). Just want to rule out media cache issues on your webserver's side

yes, it doesn't resuvle any issue, i just downloaded some images and i can view some images from other server, new post's media_attachmemt is still in blur. I really don't know how to what's the problem is, my mastodon version is 4.2.9 and install it with docker

**Comment by Harvey-Ai** [comment]
below the debug info with attachment.reset_file

mastodon@d3fee6167aa8:~$ RAILS_ENV=production bin/tootctl media refresh --status=112613172512083905 --verbose
Processing 112613172187961699                                                                                    
1/1 |============================================================================================| Time: 00:00:00
Downloaded 1 media attachments (approx. 0 Bytes)
mastodon@d3fee6167aa8:~$ RAILS_ENV=production RAILS_LOG_LEVEL=debug bundle exec rails console
Chewy console strategy is `urgent`
Loading production environment (Rails 7.0.8.1)
irb(main):001:0> MediaAttachment.find(112613172187961699)
D, [2024-06-14T05:07:21.650027 #18019] DEBUG -- :   MediaAttachment Load (2.9ms)  SELECT "media_attachments".* FROM "media_attachments" WHERE "media_attachments"."id" = $1 ORDER BY "media_attachments"."id" ASC LIMIT $2  [["id"
=> 
#<MediaAttachment:0x0000783c6be8d620
 id: 112613172187961699,
 status_id: 112613172512083905,
 file_file_name: "fafbbc35f0429499.jpg",
 file_content_type: "image/jpeg",
 remote_url:
 created_at: Fri, 14 Jun 2024 04:50:40.073742000 UTC +00:00,
 updated_at: Fri, 14 Jun 2024 04:50:45.031308000 UTC +00:00,
 shortcode: nil,
 type: "image",
 file_meta:
  {"original"=>{"width"=>1440, "height"=>2464, "size"=>"1440x2464", "aspect"=>0.5844155844155844},
   "small"=>{"width"=>367, "height"=>628, "size"=>"367x628", "aspect"=>0.5843949044585988}},
 account_id: 112608251751646024,
 description: nil,
 scheduled_status_id: nil,
 blurhash: "UYD1QrIVn#V@kvMwxtR+nMIUogayV:adWBs+",
 processing: "complete",
 file_storage_schema_version: 1,
 thumbnail_file_name: nil,
 thumbnail_content_type: nil,
 thumbnail_file_size: nil,
 thumbnail_updated_at: nil,
 thumbnail_remote_url: nil>
irb(main):002:0> attachment = MediaAttachment.find(112613172187961699), 112613172187961699], ["LIMIT", 1]]
=> 
#<MediaAttachment:0x0000783c6c6d94c8
...
irb(main):003:0> 
irb(main):004:0* 
=> nil
irb(main):005:0> attachment.reset_file!
D, [2024-06-14T05:08:12.637221 #18019] DEBUG -- : [httplog] GET https://files.mastodon.social/media_attachments/files/112/613/171/766/097/036/original/a4e857843a02300a.jpg completed with status code 200 in 0.816692 seconds
I, [2024-06-14T05:08:13.782871 #18019]  INFO -- : [paperclip] Trying to link /tmp/e5f60ffb9cf795aa402956154d15728b20240614-18019-fkta7q.jpg to /tmp/c2416c3519babe75dfd3be026c26d2f520240614-18019-23y1uu.jpg
I, [2024-06-14T05:08:13.783686 #18019]  INFO -- : Command :: file -b --mime '/tmp/c2416c3519babe75dfd3be026c26d2f520240614-18019-23y1uu.jpg'
I, [2024-06-14T05:08:13.792894 #18019]  INFO -- : [paperclip] Trying to link /tmp/e5f60ffb9cf795aa402956154d15728b20240614-18019-fkta7q.jpg to /tmp/e7f2df7ad263799062438ba38b0a860820240614-18019-s5r8zv.jpg
I, [2024-06-14T05:08:13.795127 #18019]  INFO -- : Command :: identify -format %m '/tmp/e7f2df7ad263799062438ba38b0a860820240614-18019-s5r8zv.jpg[0]'
I, [2024-06-14T05:08:13.858945 #18019]  INFO -- : Command :: convert '/tmp/e7f2df7ad263799062438ba38b0a860820240614-18019-s5r8zv.jpg[0]' -auto-orient -resize "367x628>" -quality 90 +profile "!icc,*" +set date:modify +set date:create +set date:timestamp -define jpeg:dct-method=float '/tmp/f2e15aeb0f654db53f308f419d5c76eb20240614-18019-80lujo'
I, [2024-06-14T05:08:14.712653 #18019]  INFO -- : Command :: convert '/tmp/f2e15aeb0f654db53f308f419d5c76eb20240614-18019-80lujo' -depth 8 RGB:-
I, [2024-06-14T05:08:16.230292 #18019]  INFO -- : [paperclip] Trying to link /tmp/f2e15aeb0f654db53f308f419d5c76eb20240614-18019-80lujo to /tmp/3918905766d69bf4979f8f730f10651820240614-18019-6fyprm
=> nil

**Comment by Harvey-Ai** [comment]
mastodon@d3fee6167aa8:~$ RAILS_ENV=production RAILS_LOG_LEVEL=debug bundle exec rails console
Chewy console strategy is `urgent`
Loading production environment (Rails 7.0.8.1)
irb(main):001:0> attachment = MediaAttachment.find(112613172187961699)
D, [2024-06-14T05:48:16.997932 #18702] DEBUG -- :   MediaAttachment Load (2.8ms)  SELECT "media_attachments".* FR, 112613172187961699], ["LIMIT", 1]]
=> 
#<MediaAttachment:0x00007838958d7ac0
...
irb(main):002:0> puts "Before reset_file: #{attachment.file.path}"
Before reset_file: /opt/mastodon/public/system/cache/media_attachments/files/112/613/172/187/961/699/original/fafbbc35f0429499.jpg
=> nil
irb(main):003:0> attachment.reset_file!
D, [2024-06-14T05:48:42.736691 #18702] DEBUG -- : [httplog] GET https://files.mastodon.social/media_attachments/files/112/613/171/766/097/036/original/a4e857843a02300a.jpg completed with status code 200 in 0.938204 seconds
I, [2024-06-14T05:48:44.040587 #18702]  INFO -- : [paperclip] Trying to link /tmp/e5f60ffb9cf795aa402956154d15728b20240614-18702-5b6m1r.jpg to /tmp/d6d9d9c6ade6b396b961bec967e9dcf220240614-18702-tkbpcx.jpg
I, [2024-06-14T05:48:44.041342 #18702]  INFO -- : Command :: file -b --mime '/tmp/d6d9d9c6ade6b396b961bec967e9dcf220240614-18702-tkbpcx.jpg'
I, [2024-06-14T05:48:44.050062 #18702]  INFO -- : [paperclip] Trying to link /tmp/e5f60ffb9cf795aa402956154d15728b20240614-18702-5b6m1r.jpg to /tmp/15dab8037b87a59143e8ca8756e5b8fc20240614-18702-mfk2be.jpg
I, [2024-06-14T05:48:44.052217 #18702]  INFO -- : Command :: identify -format %m '/tmp/15dab8037b87a59143e8ca8756e5b8fc20240614-18702-mfk2be.jpg[0]'
I, [2024-06-14T05:48:44.797708 #18702]  INFO -- : Command :: convert '/tmp/15dab8037b87a59143e8ca8756e5b8fc20240614-18702-mfk2be.jpg[0]' -auto-orient -resize "367x628>" -quality 90 +profile "!icc,*" +set date:modify +set date:create +set date:timestamp -define jpeg:dct-method=float '/tmp/fa93113f1c33eb42048d3b5b8bba092520240614-18702-ti2813'
I, [2024-06-14T05:48:45.839065 #18702]  INFO -- : Command :: convert '/tmp/fa93113f1c33eb42048d3b5b8bba092520240614-18702-ti2813' -depth 8 RGB:-
I, [2024-06-14T05:48:47.247832 #18702]  INFO -- : [paperclip] Trying to link /tmp/fa93113f1c33eb42048d3b5b8bba092520240614-18702-ti2813 to /tmp/318fe17822357723ecb0b09d4f89406420240614-18702-dj5wmf
=> nil
irb(main):004:0> puts "After reset_file: #{attachment.file.path}"
After reset_file: /opt/mastodon/public/system/cache/media_attachments/files/112/613/172/187/961/699/original/962ae5976c3a97ba.jpg

**Comment by Harvey-Ai** [comment]
> Did this actually fix your issue? Keep in mind that `--force` will **always** result in tootctl (re-)downloading said images, the fact it downloaded 6.16MB this run doesn't mean it has resolved any actual issues.
> 
> > so the problem is bandwidth intensive?
> 
> Constantly running this command with `--force` is not an acceptable solution, if this actually resolved any issues there is a deeper problem that should be looked into. I've never seen mastodon mark external content as successfully processed (where it doesn't consider any of the files in need to be redownloaded) through tootctl while this is not actually the case.
> 
> If you click on any of the images that are "blurry", does Mastodon redirect you to the image hosted on the source instance, or does it give you a 404 (originating from your host). Just want to rule out media cache issues on your webserver's side

sorry, i found the reason, i mistoken the sidekiq and web volumes, and usde two seperate volume for them that makes sidekiq downloaded images in sidekiq container.
