### ISSUE TITLE
Better control over who's following me

### ISSUE THREAD

**Issue by jonpincus** [tootsuite/mastodon#2187]
People who are at risk of being harassed - as well as anybody else who wants to use Mastodon for "friends-only" conversations - need finer-grained control over who's following them, in order to be able to use "private" messages effectively.  For example:

- disallow follow requests: from anybody, from people on specific instances, or from people that _aren't_ on a list of approved instances
- ~~have an option to approve or disapprove potential followers~~ *update: wxcafe points out that this is alrady supported by private accounts*
- "force unfollow" somebody I don't want following me

(Apologies if this duplicates an existing issue.  I did some searching and couldn't find it.  #698 discusses anti-harassment design in general, but is more about documenting than adding new functionality.)

* * * *

- [*] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [*] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by expenses** [comment]
I'm not sure if this is possible, given how 'following' in Mastodon is basically subscribing to an rss feed. You can't really force someone to not check if you've posted anything. Even if a change was implemented that allowed you to send 'force unfollow' commands to other instances, there is no guarantee that the instance will obey them, so it's not reliable.

As it stands at the moment, Mastodon (without making significant changes) just isn't that great for private conversations.

**Comment by wxcafe** [comment]
This is possible by setting your account to private? I believe that's what you're looking for 
![screenshot from 2017-04-20 09-09-55](https://cloud.githubusercontent.com/assets/3009327/25217945/283a983e-25a9-11e7-8f24-f5cde202d63c.png)

**Comment by expenses** [comment]
@wxcafe How does the 'manually approve followers' bit of that option actually work though?

**Comment by wxcafe** [comment]
Exactly like on twitter : you click "make account private", when people want to follow you they don't get your (non-public) toots immediately, and then you get this

<img width="323" alt="screen shot 2017-04-20 at 10 45 56" src="https://cloud.githubusercontent.com/assets/3009327/25221949/389fe298-25b7-11e7-97ce-ceba1515f9ef.png">

and then you can allow/decline follow requests

<img width="321" alt="screen shot 2017-04-20 at 10 46 03" src="https://cloud.githubusercontent.com/assets/3009327/25222119/cd0a7010-25b7-11e7-9729-01019831dfb1.png">

We should add this to the documentation and I'm opening an issue there : tootsuite/documentation#109

**Comment by jonpincus** [comment]
@wxcafe thanks!  it looks like private accounts take care of the middle bullet (approving follower requests) so I updated the issue accordingly.  and yes better documentation would be useful so thanks for opening that issue!

@expenses i'm not sure of the underlying implementation, for all i know this may turn out to be impossible ... but i still want it :)

**Comment by wxcafe** [comment]
Okay so about the third point, you can block a person and then unblock them, and it does that force unfollow thing. About the first, there's a PR in the works (#501) which wasn't getting much love, so I updated the labels on it.

**Comment by jonpincus** [comment]
Great, thanks!

**Comment by wxcafe** [comment]
I made the "using a private account" guide in the documentation as a PR, it's at tootsuite/documentation#121. Did that discussion answer your questions? If so, please close the issue :)

**Comment by jonpincus** [comment]
Thanks for adding the discussion.  There's still the other two bullets, so I don't think this issue is ready to close.   (even once #501 is implemented, there's more that's needed for the first item.)

**Comment by wxcafe** [comment]
Wouldn't the third bullet be solved with the "block/unblock" thing? Also, you might want to take a look at #2111. Finally, #501 was replaced by #2381 :)

**Comment by jonpincus** [comment]
#2111 addresses "remove follower" (although it seems to introduce a new concept "locked account"?)   #2381 seems very useful but still doesn't give the ability to disallow follow requests from unblocked domains ... I guess it's a reasonable approximation, so I'll close this.  Thanks for the discussion!
