### ISSUE TITLE
Vagrant up failure

### ISSUE THREAD

**Issue by techmaniack** [tootsuite/mastodon#2749]
I am trying to setup mastodon on my local machine using vagrant but getting this error

> ...
> ==> default: yarn install v0.23.4
> ==> default: [1/4] Resolving packages...
> ==> default: [2/4] Fetching packages...
> ==> default: error postcss-smart-import@0.6.12: The engine "node" is incompatible with this module. Expected version ">=6.0.0".
> ==> default: error Found incompatible module
> ...

OSX 10.12.4
vagrant 1.9.4

 
* * * *

- [* ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by mjankowski** [comment]
Probably related - https://github.com/tootsuite/mastodon/pull/2742 - changes vagrant to use node v6

**Comment by theophilus79** [comment]
Same issue here. Have tried with --force and --production as well, to no avail.

**Comment by techmaniack** [comment]
After fixing the node installation from
`curl -sL https://deb.nodesource.com/setup_4.x | sudo bash -`
to
`curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -`

the setup continued fine but there is another issue now which I guess is relating to static content not being served properly.

![screen shot 2017-05-04 at 3 34 40 am](https://cloud.githubusercontent.com/assets/524248/25683729/40113698-307b-11e7-83bf-f36bcbe03d5c.png)

Where should I be looking?

**Comment by abcang** [comment]
The webpack-dev-server uses port 8080 for distribution of static content.
Vagrant performs port forwarding on port 8080, and this problem is solved with the latest master.

**Comment by techmaniack** [comment]
I pulled the new code, destroyed the previous vagrant machine and did a vagrant up. It still doesn't work.

> ➜  mastodon git:(master) ✗ vagrant ssh -c "cd /vagrant && foreman start"
> 15:58:15 web.1     | started with pid 30410
> 15:58:15 stream.1  | started with pid 30411
> 15:58:15 webpack.1 | started with pid 30413
> 15:58:16 webpack.1 | sh: 1: /vagrant/node_modules/.bin/webpack-dev-server: not found
> 15:58:16 stream.1  | yarn run v0.23.4
> 15:58:16 stream.1  | $ babel-node ./streaming/index.js --presets es2015,stage-2
> 15:58:17 webpack.1 | exited with code 127
> 15:58:17 system    | sending SIGTERM to all processes
> 15:58:17 stream.1  | sh: 1: babel-node: not found
> 15:58:17 stream.1  | error Command failed with exit code 127.
> 15:58:17 stream.1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 15:58:17 web.1     | terminated by SIGTERM
> 15:58:17 stream.1  | terminated by SIGTERM
> Connection to 127.0.0.1 closed.

**Comment by mjankowski** [comment]
Try `vagrant provision` ?

**Comment by techmaniack** [comment]
Tried `vagrant provision` still getting the same error when trying to run foreman.

Also, `vagrant destroy -f && vagrant up` should have taken care of provisioning the vm ?

**Comment by abcang** [comment]
It seems that `node_modules` is not properly installed.
What happens when you run `vagrant ssh -c "cd /vagrant && yarn install"`?

**Comment by techmaniack** [comment]
Yes I think node_modules is the issue.

> $ vagrant ssh -c "cd /vagrant && yarn install"
> ..
> error An unexpected error occurred: "EACCES: permission denied, rmdir '/vagrant/node_modules/eslint/node_modules/.bin'".
> ..

I will retry tomorrow by cloning mastodon to a different location. The current project seems to have files from the previous vagrant vm.

**Comment by techmaniack** [comment]
It works!

Thanks for the help.
