### ISSUE TITLE
Provide relaxed sanitisation on ActivityPub 'Article' 

### ISSUE THREAD

**Issue by zotlabs** [tootsuite/mastodon#5022]
As mentioned in https://github.com/swicg/general/issues/20 , there is a content federation conflict between 'microblog' projects and projects that allow rich content and multi-media authoring. Microblogs are tending to separate media from the text content, and multi-media apps cannot easily present their content on these systems as the media is filtered out and/or removed from its positional context in the text.

As a workaround, we've been considering using the 'Article' type in ActivityPub for this rich multi-media content and allow 'Note' to be text plus separate media (as it is currently being used by Mastodon). It appears from reading source that Mastodon applies the same input filtering to both types. We would like to relax the filtering on the Article type to include img, video, and audio at minimum. Tables and lists would be desirable.  The Sanitize filter apparently provides such a RELAXED filter (which is used as a basis for the MASTODON_OEMBED filter definition, and looks workable without significant modification while still providing XSS sanitisation). 

The main issues we have with trying to make our content work within the current filter are 1) losing context if you have images separated by text, 2) losing image sizes, losing tables and other rich content creations, and 3) modifying the content to fit within Mastodon's content rules can invalidate signatures; especially if the content was submitted as a comment from a different network.  Currently if we provide content with a photo, Mastodon strips the photo. If we split the photo from the text and turn it into an attachment, we invalidate the signature. The 'Article' type seems the best way for both types of content systems to co-exist in the same network, with 'Note' carrying restrictions as it does now. Of course systems should filter for potentially harmful content. The current filtering is perfect for microblogs but potentially unworkable for cross-platform federation with other content producers.

If implemented this also opens the possibility of Mastodon providing/sharing more rich-media content going forward.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [ ] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (If you're a user, don't worry about this).

**Comment by Gargron** [comment]
I believe what we do now is convert an Article object into title + URL to the original, so you can view the post as it's supposed to be, rather than trying to display it internally. So, I think this is resolved.

**Comment by annando** [comment]
From my point of view it is not completely resolved, since the solution doesn't cover non public articles. See this issue: https://github.com/mastodon/mastodon/issues/8892

**Comment by julianlam** [comment]
We are beginning to see some movement again on this distinction — [it was discussed at the May ForumWG meeting](https://community.nodebb.org/post/99493)

We would love to include the Mastodon team (@renchap?) in these discussions.

**Comment by renchap** [comment]
We have this on our medium-term roadmap, but at the moment I do not have the time available to really participate or follow those discussions. Maybe @ClearlyClaire has some time for this, but please note that we are really struggling with resources right now. I hope this will get better soon.

@trwnh may also be an interface with us if they have time.

**Comment by julianlam** [comment]
@renchap thank you, and yes, I am aware of the limited resources. My main concern is including you (even passively and asynchronously) in the discussions.

End of the day Mastodon has every right to present content how it wishes. With the increasing number of forum and blogging softwares entering the fediverse, it is increasingly likely that you'll encounter more content containing richer HTML than Mastodon prefers, that's all.

**Comment by renchap** [comment]
To provide some additional context, this is not yet 100% set in stone but we intend to have a big focus around posts, replies & timelines in the next release. This includes how posts are displayed (in and out of timelines), and we intend to have a go at better displaying non-microblogging content in Mastodon (initial target is long-form content). This may involve having a "read more" link in statuses, that opens a modal displaying the full content (ideas are either using an embedded HTML-based "long" content field, or an attribute in the content to get an URL to embed in an iframe).

Those are only plans and ideas, but we really want to improve this. I am unsure how it relates to the ForumWG work, but it may help to know what we may work on.
