### ISSUE TITLE
hard-coded styles

### ISSUE THREAD

**Issue by wchristian** [tootsuite/mastodon#584]
Please make this proper CSS:

```html
<div data-reactroot="" style="flex: 0 0 auto;display: flex;flex-direction: column;width: 100%;height: 100%;background: rgb(26, 28, 35);"><div class="tabs-bar" style="background: rgb(55, 59, 74); flex: 0 0 auto; overflow-y: auto;">
```

**Comment by Gargron** [comment]
Can this be marked as resolved now?

**Comment by wchristian** [comment]
Hrm, up to you honestly. You moved the colors out, but i still see plenty other hard-coded things, like margins and such.

Not concerned about those, but you might want to target those too.

**Comment by wchristian** [comment]
Some more hard-coded styles:

- divs for the media bits in statuses
- the div for the buttons in statuses

With those i'm less concerned about the hard-coding, and more about the lack of classes on them (which could overwrite the hard-coding).

**Comment by stephenburgess8** [comment]
I can pick this up.

**Comment by ashfurrow** [comment]
Looks like this has been fixed as of https://github.com/tootsuite/mastodon/pull/2338 being merged. If it's not fixed to your satisfaction, please re-open. Thanks!
