### ISSUE TITLE
Disallow zooming on mobile

### ISSUE THREAD

**Issue by noiob** [tootsuite/mastodon#612]
Since Mastodon adapts to different screen sizes quite well, and can be set up as a webapp [on iPhones] it would be helpful to disallow zooming.

The kind of behavior I'm experiencing is the following:
- go to the Compose tab, the toot field gets focused automatically
- mobile Safari decides to zoom in a bit to show the input field better
- the Mastodon layout adapts to the new view borders, leading to the view looking like it would look on a slightly smaller screen (the text gets bigger and the top bar gets compressed a bit)
- if I want it to look normal again, I have to do a two-finger zoom-out gesture

Disallowing zooming would fix this issue and help with Mastodon feeling more like a native app.

**Comment by zcdunn** [comment]
A simpler answer seems to be making font size at least 16px. 
http://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

Disabling zooming is heavy handed and takes away a feature from users who may expect it.

**Comment by noiob** [comment]
The text just appears bigger because of the zoom. It doesn't change font size.

**Comment by zcdunn** [comment]
@noiob I think you misunderstood my comment. I'm saying the font size of inputs can be set,by the dev, to at least 16px. Safari seems to zoom in only if font size is less than that.

**Comment by mitchellurgero** [comment]
This issue might be present on android and in that case:
Setting the meta:
<meta name="viewport" content="width=device-width, initial-scale=1">

Should resolve this issue completely for all devices with small screens and a recent browser.

**Comment by mitchellurgero** [comment]
I see this is set already - What browser are you using?

**Comment by noiob** [comment]
If it's possible to stop the zoom-in-when-focusing-input behavior I'd strongly favor not disabling zooming as well. The viewport tag does not resolve the issue on the current mobile Safari on an iPhone 5.

**Comment by mitchellurgero** [comment]
Zoom is working properly for mobile chrome (As in I cannot zoom in past the original WxH.

**Comment by noiob** [comment]
I think af5cb0f broke this again, for some reason, because it's been working and now it's not working (in mobile Safari, iPhone 5, newest iOS)
