### ISSUE TITLE
LDAP support still needs LDAP_ENABLED=true set outside .env

### ISSUE THREAD

**Issue by sigmaris** [tootsuite/mastodon#6790]
After #6663 was merged, and https://github.com/tootsuite/documentation/commit/c1af30a86b4a5d0e4e1f7997e47235766a76959c was changed in the documentation, I assumed the requirement to set `LDAP_ENABLED=true` in the process environment was gone, and it could be set in the `.env.production` file alone. I'm on v2.3.1 now and I tried removing the `Environment="LDAP_ENABLED=true"` line from my systemd .service files. But this introduces a problem when I'm viewing the root URL on my instance while logged out - I see this error in the log:

```
bundle[5675]: [a71fed94-3527-48e9-aac6-7e87216f6585] method=GET path=/ format=html controller=HomeController action=index status=401 duration=1.48 view=0.00 db=0.00
bundle[5675]: [a71fed94-3527-48e9-aac6-7e87216f6585]
bundle[5675]: [a71fed94-3527-48e9-aac6-7e87216f6585] RuntimeError (Invalid strategy ldap_authenticatable):
bundle[5675]: [a71fed94-3527-48e9-aac6-7e87216f6585]
bundle[5675]: [a71fed94-3527-48e9-aac6-7e87216f6585] app/controllers/concerns/localized.rb:14:in `set_locale'
```

Everything appears to work fine if I have `Environment="LDAP_ENABLED=true"` line in my systemd .service file for the web process.

I suspect the issue might be related to this line being evaluated before `.env.production` takes effect, and so the whole block in that file to add ldap_authenticatable as a strategy is never run: https://github.com/tootsuite/mastodon/blob/fd385e256d1ca99fa9a6f1bd8068d083cb0e39ba/lib/devise/ldap_authenticatable.rb#L3
but I'm not very familiar with Ruby or Rails so I could well be wrong.

* * * *

- [x] I searched or browsed the repo’s other issues to ensure this is not a duplicate.
- [x] This bug happens on a [tagged release](https://github.com/tootsuite/mastodon/releases) and not on `master` (happens on v2.3.1)

**Comment by devkral** [comment]
same true for pam, I am looking for a solution. How about optional groups for such features?
see https://github.com/diaspora/diaspora/pull/7728

**Comment by devkral** [comment]
close? I looked through the code and it should be solved.

**Comment by tigre-bleu** [comment]
In current stable release 2.3.1 the issue is still there and the systemd unit file needs to be modified.

**Comment by Gargron** [comment]
It's because the class declaration is behind the conditional, that file is evaluated before .env is loaded... But that's from when LDAP was optional dependency, I think now it's OK to remove the conditional from that file.

**Comment by sigmaris** [comment]
I can confirm this issue is fixed in v2.3.2rc4, thanks @Gargron !
