### ISSUE TITLE
Boost and toot deletion interaction problem

### ISSUE THREAD

**Issue by SuliacLEGUILLOU** [tootsuite/mastodon#889]
Boosting a toot may result in bug in his deletion in some case

@Sp3r4z@mastodon.xyz, @corzntin@anticapitalist.party and I (@s18alg@hostux.social) made some test on multi-instance configuration

Reproduce :
- sp3r4z post a toot
- I boost it, then Corzntin boost it
- sp3r4z boost his own toot
- sp3r4z delete the toot

after that Corzntin can still see the deleted toot, but I can't
This doesn't look critical, and may likely be a bug comming from instance configuration, but I submit it since it may become a privacy issue.

* * * *

- [ x ] I searched or browsed the repo’s other issues to ensure this is not a duplicate.

**Comment by Gargron** [comment]
Okay, I can see this being problematic. Thank you for taking the time to test this. Off the top of my head it's probably because the "delete" notification is sent to all followers of the original author. The receivers of that "delete" remove the toot/boost. But do not forward the "delete" even further in case of boosts. A special case for such forwarding needs to be added.

**Comment by Gargron** [comment]
I have confirmed that my above assesment is incorrect. Save for network failures, a delete propagates, deleting reblogs of itself, spreading the deletes further. There were some causality related issues with deletes that were fixed since this issue was opened. Perhaps it's no longer a problem.

**Comment by unarist** [comment]
I think this problem still exists on 1.5.1. Even now, only ways to delete status from remote instance are a) push to subscribers b) salmon to mentioned accounts. Subscribers of the user who boosted will receive those "delete" message for boost itself, but not for boosted status.
